raise RuntimeError('This demos a failing conf.py')
